# Generated by Django 4.2.6 on 2023-12-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
    ]
