# Generated by Django 5.0 on 2023-12-20 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_description_post_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
