# Generated by Django 5.0 on 2023-12-20 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_reactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.AddField(
            model_name='post',
            name='reaction_dislike',
            field=models.ManyToManyField(related_name='reactions_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='reaction_like',
            field=models.ManyToManyField(related_name='reactions_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
