# Generated by Django 5.0 on 2023-12-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rank_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, default='common', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rank'),
        ),
    ]
