# Generated by Django 4.2.7 on 2023-11-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie_tresc', models.CharField(max_length=250)),
                ('data_publikacji', models.DateTimeField(verbose_name='opublikowane')),
            ],
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybor_tresc', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankiety.pytanie')),
            ],
        ),
    ]
